import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/navbar/navbar'
import Footer from './components/navbar/footer'



export const metadata: Metadata = {
  title: 'crud-login-system',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
        <Footer/>
        </body>
    </html>
  )
}
